name: Check HUDs

on:
  push:
  pull_request:

jobs:
  check:
    name: Check HUDs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        key: ${{ github.ref }}
        path: .cache
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
    - name: Check
      run: |
        pnpm i
        pnpm lint
        pnpm check
